---
logs_root: /var/log/nginx/
nginx_user: www-data
strip_www: true

nginx_sites: []
nginx_app_dir: "{{ COMMON_APP_DIR }}/nginx"
nginx_data_dir: "{{ COMMON_DATA_DIR }}/nginx"
nginx_server_static_dir: "{{ nginx_data_dir }}/server-static"
nginx_conf_dir: "{{ nginx_app_dir }}/conf.d"
nginx_log_dir: "{{ COMMON_LOG_DIR }}/nginx"
nginx_sites_available_dir: "{{ nginx_app_dir }}/sites-available"
nginx_sites_enabled_dir: "/etc/nginx/sites-enabled"

nginx_template_dir: "django/app/nginx/sites-available"

nginx_djangoapp_gunicorn_port: 9000
nginx_djangoapp_gunicorn_hosts:
  - 127.0.0.1
nginx_djangoapp_data_dir: djangoapp

NGINX_LOG_FORMAT_NAME: 'p_combined'

DJANGOAPP_NGINX_HOSTNAME: '~^app.*'
NGINX_SET_X_FORWARDED_HEADERS: True
