---
#
# DjangoApp Configuration
##
# Defaults for role djangoapp
# vars are namespace with the module name.
#

# Used at the supervisor conf to set the gunicorn --max-requests
DJANGOAPP_MAX_REQ: !!null

DJANGOAPP_WORKERS:
  web: 2

DJANGOAPP_SETTINGS: 'app.settings.prod'
DJANGOAPP_LANG: 'en_US.UTF-8'

DJANGOAPP_NGINX_PORT: 80

# MySQL DB
DJANGOAPP_MYSQL_HOST: localhost

DJANGOAPP_MYSQL_DB_NAME: 'django_db'
DJANGOAPP_MYSQL_USER: 'DJANGOAPP'
DJANGOAPP_MYSQL_PASSWORD: 'securePassword123'


# Security
DJANGOAPP_SECRET_KEY: "make_this_key_secure_in_group_vars"

# Memcache
DJANGOAPP_MEMCACHE: [ 'localhost:11211' ]

# Space to load extra env and auth vars
# DJANGOAPP_ENV_EXTRA: []
# DJANGOAPP_AUTH_EXTRA: []

# Email
DJANGOAPP_EMAIL_HOST_USER: mandril_user@myhost.co
DJANGOAPP_EMAIL_HOST_PASSWORD: password

djangoapp_role_name: djangoapp

djangoapp_user: djangouser
djangoapp_data_dir: "{{ COMMON_DATA_DIR }}/djangoapp"
djangoapp_app_dir: "{{ COMMON_APP_DIR }}/djangoapp"
djangoapp_code_dir: "{{ djangoapp_app_dir }}/django.app"
djangoapp_venvs_dir: "{{ djangoapp_app_dir }}/venvs"
djangoapp_venv_dir: "{{ djangoapp_venvs_dir }}/django.app"
djangoapp_venv_bin: "{{ djangoapp_venv_dir }}/bin"
djangoapp_deploy_path: "{{ djangoapp_venv_bin }}:{{ djangoapp_code_dir }}/bin:{{ djangoapp_code_dir }}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
djangoapp_main_log_path: "{{ COMMON_LOG_DIR }}/django.log"

djangoapp_source_repo: "git@github.com:eduNEXT/django-example-app.git"
djangoapp_version: "master"
djangoapp_requirements_file: "{{ djangoapp_code_dir }}/requirements/prod.txt"

djangoapp_deployment_ssh_key: "{{ secure_dir }}/keys/myDeploymentKey"
djangoapp_git_identity_dest: "/etc/{{ djangoapp_role_name }}.git-identity"

djangoapp_gunicorn_port: 9000
djangoapp_gunicorn_host: 127.0.0.1

djangoapp_environment:
  DJANGO_SETTINGS_MODULE: "app.settings.prod"
  LANG: "{{ DJANGOAPP_LANG }}"
  PATH: "{{ djangoapp_deploy_path }}"

djangoapp_localdev_user: "vagrant"
djangoapp_localdev_home: "/home/vagrant"
djangoapp_localdev_accounts:
    - { user: "{{ djangoapp_user }}", home: "{{ djangoapp_app_dir }}",
        env: "djangoapp_env", repo: "django.app" }

#
# OS packages
#

djangoapp_pkgs:
  - libmariadbclient-dev
  - libssl-dev

djangoapp_env_config:
  EMAIL_HOST: "smtp.mandrillapp.com"
  STATIC_ROOT: "{{ djangoapp_data_dir }}/staticfiles"
  LOG_FILE: "{{ djangoapp_main_log_path }}"

djangoapp_auth_config:
  STATICFILES_STORAGE: 'storages.backends.s3boto.S3BotoStorage'
  SECRET_KEY: "{{ DJANGOAPP_SECRET_KEY }}"
  EMAIL_HOST_USER: "{{ DJANGOAPP_EMAIL_HOST_USER }}"
  EMAIL_HOST_PASSWORD: "{{ DJANGOAPP_EMAIL_HOST_PASSWORD }}"
  DATABASES:
    default:
      ENGINE: 'django.db.backends.mysql'
      NAME: "{{ DJANGOAPP_MYSQL_DB_NAME }}"
      HOST: "{{ DJANGOAPP_MYSQL_HOST }}"
      USER: "{{ DJANGOAPP_MYSQL_USER }}"
      PASSWORD: "{{ DJANGOAPP_MYSQL_PASSWORD }}"
      PORT: '3306'
  CACHES:
    default: &default_generic_cache
      BACKEND:  'django.core.cache.backends.memcached.MemcachedCache'
      KEY_FUNCTION:  'util.memcache.safe_key'
      KEY_PREFIX: 'DJANGOAPP'
      LOCATION: "{{ DJANGOAPP_MEMCACHE }}"
